version: '3.8'

services:
  # 1. Main Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewPassword123
      POSTGRES_DB: login_db
    ports:
      - "5433:5432" # HOST 5433 maps to CONTAINER 5432 (Bypasses your local conflict)
    volumes:
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. Auth Backend
  backend:
    build: ./back
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=NewPassword123
      - DB_NAME=login_db
      - JWT_SECRET=your_jwt_secret
      - SHARED_SECRET_KEY=your_internal_secret_key
      # Internal Docker URLs
      - INVENTORY_URL=http://inventory:3002/api/users/sync
      - ORDER_URL=http://order-service:3003/api/orders/sync-incoming

  # 3. Inventory Service
  inventory:
    build: ./inventory
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - ./inventory:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=NewPassword123
      - DB_NAME=login_db
      - SHARED_SECRET_KEY=your_internal_secret_key

  # 4. Order Database
  order-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewPassword123
    # No ports section needed (internal only)
    volumes:
      - ./order/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 5. Order Service
  order-service:
    build: ./order
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - order-db
    environment:
      - DB_HOST=order-db
      - DB_USER=postgres
      - DB_PASSWORD=NewPassword123
      - DB_NAME=orderdb
      - SHARED_SECRET_KEY=your_internal_secret_key

  # 6. Frontend
  frontend:
    build: ./front
    ports:
      - "8080:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - backend
      - inventory