version: '3.8'

services:
  # Database Service
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewPassword123  # Match this with your .env
      POSTGRES_DB: login_db
    ports:
      - "5432:5432"
    volumes:
      # This maps your local file to the Postgres init folder
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Backend Service
  backend:
    build: ./back
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: NewPassword123
      DB_NAME: login_db

  # Frontend Service
  frontend:
    build: ./front
    ports:
      - "8080:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - backend
  #order
  product-db:
  image: postgres:15
  environment:
    POSTGRES_DB: productdb
    POSTGRES_USER: product
    POSTGRES_PASSWORD: productpass
  volumes:
    - ./product/init.sql:/docker-entrypoint-initdb.d/init.sql
