version: '3.8'

services:
  # 1. Auth Database
  auth-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewPassword123
      POSTGRES_DB: login_db
    ports:
      - "5433:5432"
    volumes:
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. Inventory Database
  inventory-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewPassword123
      POSTGRES_DB: inventory_db
    ports:
      - "5434:5432"
    volumes:
      - ./inventory/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 3. Order Database
  order-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewPassword123
      POSTGRES_DB: orderdb
    ports:
      - "5435:5432"
    volumes:
      - ./order/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 4. Auth Backend
  backend:
    build: ./back
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - auth-db
    environment:
      - DB_HOST=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=NewPassword123
      - DB_NAME=login_db
      - JWT_SECRET=your_jwt_secret
      - SHARED_SECRET_KEY=your_internal_secret_key
      - INVENTORY_URL=http://inventory:3002/api/users/sync
      - ORDER_URL=http://order-service:3003/api/orders/sync-incoming

  # 5. Inventory Service
  inventory:
    build: ./inventory
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - inventory-db
    environment:
      - DB_HOST=inventory-db
      - DB_USER=postgres
      - DB_PASSWORD=NewPassword123
      - DB_NAME=inventory_db
      - JWT_SECRET=your_jwt_secret
      - SHARED_SECRET_KEY=your_internal_secret_key
      - ORDER_SERVICE_URL=http://order-service:3003/api/orders/receive-product
      - ENABLE_GREMLIN_LATENCY=true 

  # 6. Order Service
  order-service:
    build: ./order
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - order-db
    environment:
      - DB_HOST=order-db
      - DB_USER=postgres
      - DB_PASSWORD=NewPassword123
      - DB_NAME=orderdb
      - SHARED_SECRET_KEY=your_internal_secret_key
      - INVENTORY_SERVICE_URL=http://inventory:3002/api/inventory/update-stock

  # 7. Frontend
  frontend:
    build: ./front
    ports:
      - "8080:5173"
    depends_on:
      - backend
      - inventory
      - order-service